### ISSUE TITLE
Following main() method in custom_messages.py is returning no data, causing index out of range error 

### ISSUE THREAD

**Issue by Ed-Marcavage** [agusticonesagago/custom_linkedin_messaging#4]
This code in 

`    subprocess.run(
        [
            "scrapy",
            "crawl",
            "linkedin_people_profile",
            "-a",
            f"profile={user}",
            "-O",
            "profile.json",
        ],
        check=True
    )

    with open("profile.json", encoding="utf-8") as file:
        data = json.load(file)`
        
Is causing the following error:

`custom_linkedin_messaging-app-1  |   File "/app/./api/custom_messages.py", line 60, in main
custom_linkedin_messaging-app-1  |     candidate = data[0]
custom_linkedin_messaging-app-1  | IndexError: list index out of range`

I tried with multiple profiles given, including the one in the README file.

**Comment by agusticonesagago** [comment]
@Ed-Marcavage It appears ScrapeOps is no longer functioning. I'll reach out to them to inquire about a possible solution I can put in place.

Thank you for bringing this to my attention!

**Comment by agusticonesagago** [comment]
@Ed-Marcavage I've switched our external service to Rapid AI. This change should ensure everything operates seamlessly. However, if you come across any problems, feel free to contact me through LinkedIn or email. Thank you for bringing to our attention that ScrapeOps ceased functioning.
